### ISSUE TITLE
Ores not generating

### ISSUE THREAD

**Issue by ManMadeDracon** [juraj-hrivnak/Underdog-1.12.2#1]
**Describe the bug**
It seems as though ores from most mods are not generating.

**To Reproduce**
When mining, I have not been able to find any ores such as iron or copper. I have tried going into spectator and creative mode to search but have been unable to find any ores.

**Expected behavior**
I expected to be able to find copper and aluminum to make things like the hatch in the mod charcoal pit.

(Side note: I just got github so if I'm not doing this right please tell me)
@juraj-hrivnak

**Comment by juraj-hrivnak** [comment]
So to explain, this is not an issue with ore generation. Here is how it looks like:
![2020-12-15_11 11 54](https://user-images.githubusercontent.com/71150936/102201739-c8e79900-3ec6-11eb-951d-c20d1e68b1da.png)
![2020-12-15_11 13 50](https://user-images.githubusercontent.com/71150936/102201750-cbe28980-3ec6-11eb-9bb5-9c0871083477.png)
But! There is no way that you can know that ores are generating like that. 
So I am assuming some guide book will help a lot. So in the next update, I will more focus on making some sort of guide.
This issue is reasonable, so I will close it when I release the update with the book. At the moment the only way to find out what ores are generating where is by crafting **Field Manual**.

![2020-12-15_11 45 38](https://user-images.githubusercontent.com/71150936/102205195-21b93080-3ecb-11eb-87c4-3757257016af.png)

**Comment by juraj-hrivnak** [comment]
Full tutorial - how to find ore is nearly finished. It is contained within the new guide book!
![2021-01-09_01](https://user-images.githubusercontent.com/71150936/104177153-a171e680-5408-11eb-9a69-0f3707a2256c.png)

**Comment by juraj-hrivnak** [comment]
Fixed! In latest version! (1.62)
![2021-01-13_18 55 54](https://user-images.githubusercontent.com/71150936/104490532-3fb0a880-55d1-11eb-8819-7549c3a6ad41.png)

![2021-01-13_18 55 58](https://user-images.githubusercontent.com/71150936/104490539-40e1d580-55d1-11eb-971f-3df6ad559c8e.png)
